// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KontentAiModels
{
    public partial class CallToAction
    {
        public const string Codename = "call_to_action";
        public const string TargetCodename = "target";
        public const string TextCodename = "text";

        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<Link> Target { get; set; }
        public string Text { get; set; }
    }
}