// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using Kontent.Ai.Delivery.Abstractions;
using System;
using System.Collections.Generic;

namespace KontentAiModels
{
    public partial class Link 
    {

    }
}