// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class CallToAction
    {
        public const string Codename = "call_to_action";
        public const string TargetCodename = "target";
        public const string TextCodename = "text";

        public ContentItemSystemAttributes System { get; set; }
        public IEnumerable<object> Target { get; set; }
        public string Text { get; set; }
    }
}