// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class Chunk
    {
        public const string Codename = "chunk";
        public const string BodyCodename = "body";
        public const string HeadlineCodename = "headline";

        public string Body { get; set; }
        public string Headline { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}