// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class Link
    {
        public const string Codename = "link";
        public const string AnchorLinkCodename = "anchor_link";
        public const string ExternalUrlCodename = "external_url";
        public const string IconCodename = "icon";
        public const string InternalLinkCodename = "internal_link";
        public const string LabelCodename = "label";
        public const string LinkTypeCodename = "link_type";

        public string AnchorLink { get; set; }
        public string ExternalUrl { get; set; }
        public IEnumerable<Asset> Icon { get; set; }
        public IEnumerable<object> InternalLink { get; set; }
        public string Label { get; set; }
        public IEnumerable<TaxonomyTerm> LinkType { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}