name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install NPM dependencies and build *.less files
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
      working-directory: ./DancingGoat
    - run: npm run build
      working-directory: ./DancingGoat
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Codecov
      uses: codecov/codecov-action@v1
    - name: Build self-contained apps for Windows, Linux, and macOS
      shell: pwsh
      run: ./publish.ps1
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "Web sites"
        path: ./artifacts
    # Used for testing sample app with sample project data in i.e. QA environment - reach out to Kontent DevOps for more information    
    - name: Upload to blob storage used for QA environment testing
      if: github.ref == 'refs/heads/master'
      uses: fixpoint/azblob-upload-artifact@v4
      with:
        connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        container: kontent-sample-app-net
        cleanup: true
        name: kontent-sample-app-net
        path: ./artifacts
